language: node_js

node_js:
  - 'lts/*'

cache:
  directories:
    - '$HOME/.npm'

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1

before_install:
  - npm config set loglevel warn
  - cp sample.env .env

install: npm ci

before_script:
  - npm run ensure-env

jobs:
  include:
    - stage: Lint javaScript
      script:
        - npm run lint

    - stage: Unit and Integration tests
      script: npm test
