name: Crowdin Curriculum Download
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  i18n-download-curriculum-translations:
    name: Learn
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      ##### Download Chinese #####
      - name: Crowdin Download Chinese Translations
        uses: crowdin/github-action@master
        # options: https://github.com/crowdin/github-action/blob/master/action.yml
        with:
          # uploads
          upload_sources: false
          upload_translations: false
          auto_approve_imported: false
          import_eq_suggestions: false

          # downloads
          download_translations: true
          download_language: zh-CN
          skip_untranslated_files: true
          export_only_approved: true

          push_translations: false

          # pull-request
          create_pull_request: false

          # global options
          config: './config/crowdin/curriculum/crowdin.yml'
          base_url: ${{ secrets.CROWDIN_BASE_URL_FCC }}

          # Uncomment below to debug
          # dryrun_action: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}

      ##### Download Espanol #####
      - name: Crowdin Download Espanol Translations
        uses: crowdin/github-action@master
        # options: https://github.com/crowdin/github-action/blob/master/action.yml
        with:
          # uploads
          upload_sources: false
          upload_translations: false
          auto_approve_imported: false
          import_eq_suggestions: false

          # downloads
          download_translations: true
          download_language: es-EM
          skip_untranslated_files: true
          export_only_approved: true


          commit_message: 'chore(i8n,learn): processed translations'
          localization_branch_name: i18n-sync-learn
          push_translations: true

          # pull-request
          create_pull_request: false

          # global options
          config: './config/crowdin/curriculum/crowdin.yml'
          base_url: ${{ secrets.CROWDIN_BASE_URL_FCC }}

          # Uncomment below to debug
          # dryrun_action: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}

      # Generate PR - all languages should go ABOVE this. #
      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_ACTIONS_CAMPERBOT_PA_TOKEN }}
          branch: i18n-sync-learn
          title: 'Crowdin Sync Curriculum'
          body: |
            This PR autogenerated by Crowdin
          labels: |
            crowdin-sync
            scope: i18n
            scope: learn
          reviewers: |
            RandellDawson
            nhcarrigan
          draft: false

      - name: Validate PR output
        run: |
          echo "Pull Reqeust Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
