name: Crowdin Curriculum Upload
on:
  workflow_dispatch:
  schedule:
    # runs everyday at 11:30 AM UTC
    - cron: '30 11 * * *'

jobs:
  i18n-upload-curriculum-files:
    name: Learn
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci -w=tools/crowdin --ignore-scripts

      - name: Crowdin Upload
        uses: crowdin/github-action@master
        # options: https://github.com/crowdin/github-action/blob/master/action.yml
        with:
          # uploads
          upload_sources: true
          upload_translations: false
          auto_approve_imported: false
          import_eq_suggestions: false

          # downloads
          download_translations: false

          # pull-request
          create_pull_request: false

          # global options
          config: './config/crowdin/curriculum/crowdin.yml'
          base_url: ${{ secrets.CROWDIN_BASE_URL_FCC }}

          # Uncomment below to debug
          # dryrun_action: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}

      - name: Remove Deleted English Curriculum Files From Crowdin
        uses: ./tools/crowdin/actions/remove-deleted-files
        env:
          CROWDIN_API_URL: 'https://freecodecamp.crowdin.com/api/v2/'
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}

      - name: Hide Non-Translated Strings
        uses: ./tools/crowdin/actions/hide-non-translated-strings
        env:
          CROWDIN_API_URL: 'https://freecodecamp.crowdin.com/api/v2/'
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}

      - name: Hide Example Link in Nest an Anchor Element challenge
        uses: ./tools/crowdin/actions/hide-specific-string
        with:
          filename: 'basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.md'
          string-content: Here's a <a href="https://www.freecodecamp.org" target="_blank" mark="crwd-mark">link to www.freecodecamp.org</a> for you to follow.
        env:
          CROWDIN_API_URL: 'https://freecodecamp.crowdin.com/api/v2/'
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}

      - name: Unhide Title of Use && For a More Concise Conditional
        uses: ./tools/crowdin/actions/unhide-specific-string
        with:
          filename: 'react/use--for-a-more-concise-conditional.md'
          string-content: 'Use &amp;&amp; for a More Concise Conditional'
        env:
          CROWDIN_API_URL: 'https://freecodecamp.crowdin.com/api/v2/'
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CURRICULUM }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
