name: CI - E2E - Web browser
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - 'main'
      - 'next-**'
  workflow_dispatch:

jobs:
  cypress-run:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        #browsers: [chrome, firefox, electron]
        browsers: [chrome]
        node-version: [18.x]
        # include:
        #   - browsers: electron
        #     spec: cypress/e2e/default/learn/challenges/projects.ts

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
      # We need mailhog to catch any emails the api tries to send.
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025

    steps:
      - name: Set Action Environment Variables
        run: |
          echo "CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Checkout Source Files
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Unpack Client Artifact
        run: |
          wget -q https://freecodecamp-bucket-testing.s3.eu-west-1.amazonaws.com/client-artifact.tar
          tar -xf client-artifact.tar
          rm client-artifact.tar

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ matrix.node-version }}
          # cypress-io/github-action caches the store, so we should not cache it
          # here.

      - name: Set freeCodeCamp Environment Variables
        run: cp sample.env .env

      - name: Install and Build
        env:
          REDEFINE_AUTH: "e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a"
          REDEFINE_DEBUG_MODE: "true"
        run: |
          pnpm install
          pnpm run create:config
          pnpm run build:curriculum
          pnpm run build:server
          # we can't use the regular pip since we want to send to staging so we need a staging cert
          # pip install redefine --index-url https://redefine.dev/pip/
          pip install ${GITHUB_WORKSPACE}/redefine-0.15.1.post9-py3-none-manylinux1_x86_64.whl
          redefine config set environment=staging
          redefine config set redefine_address=dune-tf-staging.redefine.dev
          redefine config set stable_branch=main
          redefine config set dry_run=true
          redefine config set log_to_file=true
          redefine config set log_file_path="/tmp/redefine.log"
          redefine start --discover --cypress --verbose
          # cat cypress.config.js
          # cat cypress/support/e2e.js

          # this is only a dry run so we don't need all other deps
          echo "running cypress tests: "
          npx cypress run || true

      - name: Seed Database
        run: pnpm run seed


        
      - name: Cypress run dry run
        uses: cypress-io/github-action@v4
        with:
          record: ${{ env.CYPRESS_RECORD_KEY != 0 }}
          env:  REDEFINE_AUTH=e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a
          start: pnpm run start-ci
          wait-on: http://localhost:8000
          wait-on-timeout: 1200
          config: baseUrl=http://localhost:8000
          browser: ${{ matrix.browsers }}
          # spec:  cypress/e2e/default/learn/challenges/code-storage.ts
      
      - name: Install and Build
        env:
          REDEFINE_AUTH: "e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a"
        run: |
          # we can't use the regular pip since we want to send to staging so we need a staging cert
          # pip install redefine --index-url https://redefine.dev/pip/
          # pip install ${GITHUB_WORKSPACE}/redefine-0.14.17.post6-py3-none-manylinux1_x86_64.whl
          # redefine config set environment=staging
          # redefine config set redefine_address=dune-tf-staging.redefine.dev
          # redefine config set stable_branch=main
          redefine config set dry_run=false
          # need to run redefine after re-setting config
          redefine start --discover --cypress --verbose

      - name: Cypress run tests
        uses: cypress-io/github-action@v4
        with:
          record: ${{ env.CYPRESS_RECORD_KEY != 0 }}
          env:  REDEFINE_AUTH=e88afb65-65ef-4798-bc9d-db4c5342f7f3::163bf879-4060-4636-9fb6-49161e68095a
          start: pnpm run start-ci
          wait-on: http://localhost:8000
          wait-on-timeout: 1200
          config: baseUrl=http://localhost:8000
          browser: ${{ matrix.browsers }}
          # spec:  cypress/e2e/default/learn/challenges/code-storage.ts
    

      - name: print redefine logs
        run: |
          echo "Redefine Daemon Log"
          cat /tmp/redefine_daemon.log || true
          echo "Redefine plugin Log"
          cat "/tmp/redefine_plugin.log" || true
           
