name: Synch Changes to New Repo

# Deploy pipeline rules when a PR containing changes related to
# pipeline rules is merged to the 'main' branch

"on":
  push:
    # branches:
      # - main
    # paths:
      - #TODO

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  synch-changes:
    runs-on: ubuntu-20.04
    steps:
      - name: Set Up Machine
        uses: actions/setup-python@v4
        with:          
          python-version: 3.9 
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            shared
            curriculum
          fetch-depth: 5
      - name: Setup Github
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub actions"
          git config --global http.version HTTP/1.1
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          # Replace example.com with the hostname of the machine
          # you're SSH-ing into
          # ssh-keyscan example.com >> /home/runner/.ssh/known_hosts
          # DOKKU_SSH_KEY is the name of the repository secret
          echo "${{ secrets.OTHER_REPO_SSH_TOKEN }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/github_actions
      - name: Run Git synch
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          cd ../
          git clone git@github.com:Asad-Rahim/FreeCodeCampCopy.git
          echo "${PWD}"
          ls
          bash ${PWD}/freeCodeCamp/git_synch.sh
      - name: Create PR
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GH_TOKEN: ${{ secrets.OTHER_REPO_SSH_TOKEN }}
        run: |
          ls

          cd ../FreeCodeCampCopy
          gh pr create -B sample -H main --title 'Merge main into sample' --body 'Created by Github action'